/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_ldbjni_natives_NativeDBProvider
#define _Included_net_daporkchop_ldbjni_natives_NativeDBProvider

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_ldbjni_natives_NativeDBProvider
 * Method:    destroy0
 * Signature: (Ljava/lang/String;ZZZIIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_ldbjni_natives_NativeDBProvider_destroy0
  (JNIEnv *, jclass, jstring,
   jboolean, jboolean, jboolean, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     net_daporkchop_ldbjni_natives_NativeDBProvider
 * Method:    repair0
 * Signature: (Ljava/lang/String;ZZZIIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_ldbjni_natives_NativeDBProvider_repair0
  (JNIEnv *, jclass, jstring,
   jboolean, jboolean, jboolean, jint, jint, jint, jint, jint, jint, jlong);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_ldbjni_natives_NativeDBProvider
