/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_ldbjni_natives_NativeWriteBatch
#define _Included_net_daporkchop_ldbjni_natives_NativeWriteBatch

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_ldbjni_natives_NativeWriteBatch
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_ldbjni_natives_NativeWriteBatch_init
  (JNIEnv *, jclass);

/*
 * Class:     net_daporkchop_ldbjni_natives_NativeWriteBatch
 * Method:    put0
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_ldbjni_natives_NativeWriteBatch_put0
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     net_daporkchop_ldbjni_natives_NativeWriteBatch
 * Method:    delete0
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_ldbjni_natives_NativeWriteBatch_delete0
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_ldbjni_natives_NativeWriteBatch
